### ISSUE TITLE
这个包挺好用的， 我想尝试用这个， 但有遇到问题， ViewsDir  这字段不是数组， 能不能改成数组

### ISSUE THREAD

**Issue by mei-rune** [gookit/easytpl#30]
这个包挺好用的， 我想尝试用这个， 但有遇到问题， ViewsDir  这字段不是数组， 能不能改成数组

我们的项目，按功能分成了多个目录， 但是 ViewsDir  不是数组，然后我们想配合你们的  responsed 包一块用， 就遇到麻烦了。

能不能，将  ViewsDir  这字段改成数组, 重命名为  ViewsDirs,  同时  responsed 也改一下

**Comment by inhere** [comment]
`ViewsDir` 支持多个目录了，使用逗号分隔

**Comment by inhere** [comment]
已经发布新版本
